[pytest]
norecursedirs = .* venv bin build dist node_modules *.egg-info
python_files = test_*.py *_test.py
python_classes = Test* *Test
python_functions = test_*

# Ignore specific file patterns
addopts = --ignore-glob=*.html
