#####################################
## Required configuration settings ##
#####################################

# Analysis ID
# Give a name/ID that is unique to a given analysis
# This will be the name of the folder into which all files are placed
analysis_ID: example

# Folder/Directory where where reads are stored.
read_dir: test/data/testdata_L001/

# Output directory
# The pipeline will create a folder, analysis_ID, within this output directory.
output_dir: output

# Sequencer type
# Current options are: MiSeq, NextSeq (currently unused)
sequencer: MiSeq

# Where you are running these files from (. is fine for most use cases)
run_location: .

# How long Gurobi will run before stopping itself
decomp_time_limit: 100

# Size (of total percent) subgraphs that will automatically be deleted
read_purge_percent: 5

# Threads used by solver (unique from cores called for snakemake).
# If you run snakemake with 2 cores and gurobi with 4, your total will be 8 used cores
gurobi_threads: 8

# All edges with weights at or below this number will be deleted
# See documentation to better understand what averages are
prune: 0


visualize: False
#######################
## Optional settings ##
#######################
