#####################################
## Required configuration settings ##
#####################################

# Analysis ID
# Give a name/ID that is unique to a given analysis
# This will be the name of the folder into which all files are placed
# So don't make it too long or unwieldy.
analysis_ID: Test1

# Input read directory
# Folder where where reads are stored. 
read_dir: .
#/home/example_reads/

# Output directory
# Directory where you would like the ouput files 
# for this analysis batch to be placed. 
# The pipeline will create a folder, analysis_ID, within this output directory.
output_dir: output/

# Sequencer type
# This determines the number of input files the pipeline will look for
# the pipeline will print a warning for samples
# which do not have the appropriate number
# Current options are: MiSeq, NextSeq
sequencer: MiSeq

# Reference genome
# Give the path to the reference genome file for including in the Debruijn graph
ref_genome: /projects/lw226023e/brendans_data_and_code/flow/GCF_009858895.2_ASM985889v3_genomic_notail.fna

read_purge_percent: 5
gurobi_threads: 16
#Prune edges with weights lower than or equal to this amount.
prune: 0
#######################
## Optional settings ##
#######################
