name: Snakemake CI Pipeline

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # Add other OS options if needed
    steps:
      - uses: actions/checkout@v2

      # Cache Rust dependencies
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('libs/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Set up Rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Run build script
      - run: bash build.sh

      # Install Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      # Create Conda environment
      - run: |
          eval "$(conda shell.bash hook)"
          conda env create -f environment.yml
          conda list

      # Run Snakemake pipeline
      - name: Run Snakemake pipeline
        run: snakemake -s findviralstrains.smk --configfile config_files/built_test.yaml --until Add_super --cores 1
